# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu1204-latest"
  # config.vm.box_url = "http://domain.com/path/to/above.box"
  # config.ssh.private_key_path = "id_vagrant"

  config.vm.network :private_network, ip: "192.168.56.2"
  config.vm.network :private_network, ip: "192.168.57.2"

  #config.vm.network :forwarded_port, host: 8080, guest: 80

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.name = "vagrant_foreman"
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision :shell, :path => "script.sh"

end
